-- EXCEÇÕES 

SELECT * FROM CLIENTE;

EXECUTE INCLUIR_CLIENTE(12, 'CLIENTE NOVO', '4567891235', 1, 90000);

EXECUTE INCLUIR_CLIENTE(12, 'CLIENTE NOV2', '4567891235', 1, 70000);

create or replace NONEDITIONABLE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%type;
  V_CNPJ CLIENTE.CNPJ%TYPE;
BEGIN

   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   FORMATA_CNPJ(p_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, V_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
-- É CRIADO MAIS 1 BLOCO ANTES DO END DE EXCEPTION E É FEITO DESSA FORMA PARA
-- ADICIONAR UMA EXCEÇÃO, O NOME DAS EXCEÇÕES ESTÃO NA DOCUMENTAÇÃO DO ORACLE
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('-------------------------------------');
    DBMS_OUTPUT.PUT_LINE('--------CLIENTE JA CADASTRADO--------');
    DBMS_OUTPUT.PUT_LINE('-------------------------------------');
END;

--------------------------------------------------------------
-- LANÇANDO EXCEÇÕES DA FORMA CORRETA COM A BIBLIOTECA:
-- RAZE_APPLICATION_ERROR

-- -20000 A -20999 O ORACLE PERMITE CRIARMOS OS ERRORS ORA ENTRE ESSES NUMEROS

-- NESTA PROCEDURE TRATAMOS O ERRO DE ID JÁ EXISTENTE

EXECUTE INCLUIR_CLIENTE(12, 'CLIENTE NOV2', '4567891235', 1, 70000);

create or replace NONEDITIONABLE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%type;
  V_CNPJ CLIENTE.CNPJ%TYPE;
BEGIN

   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   FORMATA_CNPJ(p_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, V_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
-- É CRIADO MAIS 1 BLOCO ANTES DO END DE EXCEPTION E É FEITO DESSA FORMA PARA
-- ADICIONAR UMA EXCEÇÃO, O NOME DAS EXCEÇÕES ESTÃO NA DOCUMENTAÇÃO DO ORACLE
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JA CADASTRADO!!!');
END;


--------------------------------------------------------------
-- TRATANDO O ERRO DE ID NULO

-- COMO NÃO TEM O NOME DA EXCEPTION DESSE CASO NA DOCUMENTAÇÃO ESTAMOS CRIANDO
-- UMA VARIAVEL DE EXCEÇÃO PARA ID NULO

EXECUTE INCLUIR_CLIENTE(NULL, 'CLIENTE NOV2', '4567891235', 1, 70000);

create or replace NONEDITIONABLE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%type;
  V_CNPJ CLIENTE.CNPJ%TYPE;
  -- CRIANDO O TIPO DA VARIAVEL COMO EXCEPTION
  E_IDNULO EXCEPTION;
  -- ADICIONANDO A VARIAVEL PARA PEGAR SOMENTE OS ERROS -1400 SENDO ELES DE ID NULO
  PRAGMA EXCEPTION_INIT(E_IDNULO, -1400);
BEGIN

   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   FORMATA_CNPJ(p_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, V_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
-- É CRIADO MAIS 1 BLOCO ANTES DO END DE EXCEPTION E É FEITO DESSA FORMA PARA
-- ADICIONAR UMA EXCEÇÃO, O NOME DAS EXCEÇÕES ESTÃO NA DOCUMENTAÇÃO DO ORACLE
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JA CADASTRADO!!!');
    -- ADICIONAMOS A VARIAVEL DE ERRRO AQUI PARA DISPARAR A EXCEÇÃO COM A MENSAGEM
    WHEN E_IDNULO THEN
        RAISE_APPLICATION_ERROR(-20015, 'IDENTIFICADOR DO CLIENTE NULO');
END;

--------------------------------------------------------------
-- EXCEÇÕES NÃO PREVISTAS

create or replace NONEDITIONABLE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%type;
  V_CNPJ CLIENTE.CNPJ%TYPE;
  E_IDNULO EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_IDNULO, -1400);
BEGIN

   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   FORMATA_CNPJ(p_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, V_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JA CADASTRADO!!!');
    WHEN E_IDNULO THEN
        RAISE_APPLICATION_ERROR(-20015, 'IDENTIFICADOR DO CLIENTE NULO');
        -- ADICIONAMOS O OTHERS PARA QUAISQUER ERROS QUE ACONTECEREM
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20020, 'ERROR NÃO ESPERADO!  TEXTO ORIGINAL DO ERRO: ' || SQLERRM());
END;

EXECUTE INCLUIR_CLIENTE(18, 'CLIENTE NOVO', '4567891235', 8, 80000);


--------------------------------------------------------------
-- ERROS DO USUARIOS
-- ERROS QUE ORACLE NÃO RECONHECE COMO ERRO, MAS PARA A REGRA DE NEGOCIO PRECISA SER
-- CONSIDERADO UM ERRO

create or replace NONEDITIONABLE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%type;
  V_CNPJ CLIENTE.CNPJ%TYPE;
  E_IDNULO EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_IDNULO, -1400);
  -- ADICIONANDO VARIAVEL PARA TRATAMENTO DO ERRO
  E_FATURAMENTO_NULO EXCEPTION;
BEGIN
    -- VERIFICANDO SE O FATURAMENTO QUE VEIO DO PARAMETRO É NULO
    IF p_FATURAMENTO IS NULL THEN
    -- FORÇANDO DAR EXCEÇÃO E INDO PARA A AREA DE EXCEPTION
        RAISE E_FATURAMENTO_NULO;
    END IF;
    
   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   FORMATA_CNPJ(p_CNPJ, V_CNPJ);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, V_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'CLIENTE JA CADASTRADO!!!');
    WHEN E_IDNULO THEN
        RAISE_APPLICATION_ERROR(-20015, 'IDENTIFICADOR DO CLIENTE NULO');
    WHEN E_FATURAMENTO_NULO THEN
        RAISE_APPLICATION_ERROR(-20025, 'FATURAMENTO FOI INCLUIDO COM VALOR NULO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20020, 'ERROR NÃO ESPERADO!  TEXTO ORIGINAL DO ERRO: ' || SQLERRM());
END;

EXECUTE INCLUIR_CLIENTE(18, 'CLIENTE NOVO', '4567891235', 8, NULL);



--------------------------------------------------------------
-- FAZENDO EXERCICIOS DA AULA
-- EX 1
-- Trate o erro gerado por esse código.

DECLARE
   v_PRODUTO produto_exercicio.cod%type:= 41232;
   E_FK_VIOLADA EXCEPTION;
   PRAGMA EXCEPTION_INIT(E_FK_VIOLADA, -2292);
BEGIN
   EXCLUINDO_PRODUTO(v_PRODUTO);
EXCEPTION
    WHEN E_FK_VIOLADA THEN
        RAISE_APPLICATION_ERROR(-20015, 'PRODUTO ' || v_PRODUTO || ' POSSUI VENDA. LOGO NÃO PODE SER EXCLUIDO.');
END;


