-- CRIANDO A PROCEDURE DO CLIENTE
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE 
    (P_ID CLIENTE.ID%TYPE, 
    P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE,
    P_CATEGORIA CLIENTE.CATEGORIA%TYPE)
IS
BEGIN
    INSERT INTO CLIENTE 
    VALUES (P_ID, P_RAZAO, P_CNPJ, P_SEGMERCADO, SYSDATE, P_FATURAMENTO, P_CATEGORIA);
    COMMIT;
END;

-- EXECUTANDO A PROCEDURE DO CLIENTE
EXECUTE INCLUIR_CLIENTE (1, 'SUPERMERCADOS BOM DEMAIS', '1234567890', 1, 90000, 'MEDIO GRANDE');

--------------------------------------------------------------
-- CRIANDO LOGICA DE CATEGORIA A PARTIR DO FATURAMENTO

-- PEQUENO FATURA ATÉ 10.000
-- MEDIO ENTRE 10.001 E 50.000
-- MEDIO GRANDE ENTRE 50.001 E 100.000
-- GRANDE MAIS DE 100.000

SET SERVEROUTPUT ON

DECLARE
    V_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE := 120000;
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF V_FATURAMENTO <= 10000 THEN
        V_CATEGORIA := 'PEQUENO';
    ELSIF V_FATURAMENTO <= 50000 THEN
        V_CATEGORIA := 'MEDIO';
    ELSIF V_FATURAMENTO <= 100000 THEN
        V_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        V_CATEGORIA := 'GRANDE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('A categoria é ' || V_CATEGORIA);
END;


--------------------------------------------------------------
-- CRIANDO FUNÇÃO A PARTIR DA LOGICA FEITA EM CIMA

CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
    (P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN
    CLIENTE.CATEGORIA%TYPE
IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;    
BEGIN
    IF P_FATURAMENTO <= 10000 THEN
        V_CATEGORIA := 'PEQUENO';
    ELSIF P_FATURAMENTO <= 50000 THEN
        V_CATEGORIA := 'MEDIO';
    ELSIF P_FATURAMENTO <= 100000 THEN
        V_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        V_CATEGORIA := 'GRANDE';
    END IF;
    RETURN V_CATEGORIA;
END;

-- TESTANDO A FUNÇÃO
VARIABLE G_CATEGORIA VARCHAR2(100);
EXECUTE :G_CATEGORIA:=CATEGORIA_CLIENTE(100001);
PRINT G_CATEGORIA;


--------------------------------------------------------------
-- ADCIONANDO A FUNÇÃO NA PROCEDURE
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE 
    (P_ID CLIENTE.ID%TYPE, 
    P_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);

    INSERT INTO CLIENTE 
    VALUES (P_ID, P_RAZAO, P_CNPJ, P_SEGMERCADO, SYSDATE, P_FATURAMENTO, V_CATEGORIA);
    COMMIT;
END;

SELECT * FROM CLIENTE;

EXECUTE INCLUIR_CLIENTE (2, 'SUPERMERCADO LOPES', '1234567891', 1, 90000);

EXECUTE INCLUIR_CLIENTE (3, 'SUPERMERCADO PARANÁ', '1234567892', 1, 30000);







